<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56e53e6bc4cf2',
	'title' => 'Post Flexible Layout',
	'fields' => array (
		array (
			'key' => 'field_56e53e7a3dd01',
			'label' => 'Section',
			'name' => 'post_fl',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add a section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '56e53e8a3f758',
					'name' => 'default',
					'label' => 'Default Text',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56e53ebf3dd02',
							'label' => 'Text',
							'name' => 'fl_txt',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56e62cf39e43f',
					'name' => 'two_col_auto',
					'label' => 'Two Column (Auto)',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56ff00098iujj',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56e62d079e440',
							'label' => 'Text',
							'name' => 'fl_tc_txt',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56e62c87hnv3f',
					'name' => 'two_col',
					'label' => 'Two Columns (2 separate fields)',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56e677hlke440',
							'label' => 'Text',
							'name' => 'fl_tc_txt1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_590iop079e440',
							'label' => 'Text',
							'name' => 'fl_tc_txt2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57052ea232347',
					'name' => 'three_column',
					'label' => 'Three Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57052eac32348',
							'label' => 'Column #1 Text',
							'name' => 'col_1_txt',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_57052ebd32349',
							'label' => 'Image',
							'name' => 'col_img',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_57052ecd3234a',
							'label' => 'Column #2 Text',
							'name' => 'col_2_txt',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56e53f393dd03',
					'name' => 'slider',
					'label' => 'Image Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56e53f493dd04',
							'label' => 'Image Slides',
							'name' => 'fl_slides',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add a slide',
							'sub_fields' => array (
								array (
									'key' => 'field_56e53f6a3dd05',
									'label' => 'Image (700px wide)',
									'name' => 'fl_slide_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56e540213dd06',
									'label' => 'Lightbox Image (1280px max-width)',
									'name' => 'fl_slide_lb',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56e540663dd07',
									'label' => 'Caption',
									'name' => 'fl_slide_cap',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56e540a56dd5c',
					'name' => 'imgcol',
					'label' => 'Image Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56e540e46dd5d',
							'label' => 'Images',
							'name' => 'fl_imgcol',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 2,
							'max' => 2,
							'layout' => 'block',
							'button_label' => 'Add an image',
							'sub_fields' => array (
								array (
									'key' => 'field_56e541096dd5e',
									'label' => 'Image (335px min-width)',
									'name' => 'fl_imgcol_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56e54a0195bed',
									'label' => 'Lightbox Image (1280px max-width)',
									'name' => 'fl_imgcol_lb',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56e541966dd5f',
									'label' => 'Caption',
									'name' => 'fl_imgcol_cap',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56e541e0f85a5',
					'name' => 'txtimg',
					'label' => 'Text/Img Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56e54206f85a7',
							'label' => 'Text',
							'name' => 'fl_txtimg_txt',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_56e5427ff85a8',
							'label' => 'Image (440px wide)',
							'name' => 'fl_txtimg_img',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56e54353f85aa',
							'label' => 'Image first?',
							'name' => 'fl_txtimg_rtl',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56e5936df20e1',
					'name' => 'full_bleed',
					'label' => 'Full Bleed Image/Video',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59999087uyttr',
							'label' => 'Image/Video Content',
							'name' => 'group_img',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e59379f20e2',
									'label' => 'Image (3000 x 3000 reccomended min-dimensions)',
									'name' => 'fl_fb_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'return_format' => 'array',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => '',
									'key' => 'field_5a78890iiolkm',
									'label' => 'Video',
									'name' => 'video',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
								),
								array (
									'key' => 'field_56e593d4f20e3',
									'label' => 'Caption',
									'name' => 'fl_fb_cap',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
						array (
							'key' => 'field_599987uyjhn39',
							'label' => 'Call To Action',
							'name' => 'group_cta',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56ff89ff77653',
									'label' => 'CTA Title',
									'name' => 'cta_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_566689uikjh3',
									'label' => 'CTA Text',
									'name' => 'cta_text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
								array (
									'key' => 'field_5ddmkkknc003',
									'label' => 'CTA Button',
									'name' => 'cta_btn',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '52e5877yhsse1',
					'name' => 'video',
					'label' => 'Video (Modal)',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5ab3bede78477',
							'label' => 'Content',
							'name' => 'group_content',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5ab3beeb78478',
									'label' => 'Video URL',
									'name' => 'videourl',
									'type' => 'oembed',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'width' => '',
									'height' => '',
								),
							),
						),
						array (
							'key' => 'field_5ab3bf567847a',
							'label' => 'Preview Image',
							'name' => 'group_preview_img',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5ab3bf9a7847b',
									'label' => 'Preview Image',
									'name' => 'preview_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56effgls8761',
					'name' => 'accordion',
					'label' => 'Accordion',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5ab3b38458938',
							'label' => 'Content',
							'name' => 'acc_content',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5ab3b1f6211a7',
									'label' => 'Section Title',
									'name' => 'section_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5ab3b219211a8',
									'label' => 'Section Text',
									'name' => 'section_text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
						
						array (
							'key' => 'field_5ab3b3b358939',
							'label' => 'Accordion',
							'name' => 'acc_group',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5ab3b25c211a9',
									'label' => 'Accordion Items',
									'name' => 'acc_items',
									'type' => 'flexible_content',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layouts' => array (
										'5ab3b279b6410' => array (
											'key' => '5ab3b279b6410',
											'name' => 'item',
											'label' => 'Item',
											'display' => 'block',
											'sub_fields' => array (
												array (
													'key' => 'field_5ab3b28f211ab',
													'label' => 'Title',
													'name' => 'title',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array (
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array (
													'key' => 'field_5ab3b29d211ac',
													'label' => 'Text',
													'name' => 'text',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array (
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 1,
													'delay' => 0,
												),
											),
											'min' => '',
											'max' => '',
										),
									),
									'button_label' => 'Add an accordion item',
									'min' => '',
									'max' => '',
								),
							),
						),
					),
				),
				array (
					'key' => '56e223erfdsa',
					'name' => 'tabs',
					'label' => 'Tabbed Content',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5ab3bghjss778',
							'label' => 'Content',
							'name' => 'tab_content',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5ab3bflokp097',
									'label' => 'Section Title',
									'name' => 'section_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5ab3b89fbvvcx',
									'label' => 'Section Text',
									'name' => 'section_text',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
						
						array (
							'key' => 'field_5ab3bffd56639',
							'label' => 'Content',
							'name' => 'group_tabs',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_5abddl09811a9',
									'label' => 'Tabs',
									'name' => 'tab_items',
									'type' => 'flexible_content',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layouts' => array (
										'5ab3b279b6410' => array (
											'key' => '5ab3b2ddfahu0',
											'name' => 'item',
											'label' => 'Tab',
											'display' => 'block',
											'sub_fields' => array (
												array (
													'key' => 'field_5ab3b334321ab',
													'label' => 'Title',
													'name' => 'title',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array (
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array (
													'key' => 'field_5abbddll211ac',
													'label' => 'Text',
													'name' => 'text',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array (
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 1,
													'delay' => 0,
												),
											),
											'min' => '',
											'max' => '',
										),
									),
									'button_label' => 'Add a tab',
									'min' => '',
									'max' => '',
								),
							),
						),
					),
				),
				array (
					'key' => '57052e6132345',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57052e7032346',
							'label' => 'Gallery Shortcode',
							'name' => 'gallery_shortcode',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				)
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>