<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56e53e6b0klfj',
	'title' => 'Jump Links Flexible Layout',
	'fields' => array (
		array (
			'key' => 'field_5vn53f877dhg',
			'label' => 'Topic',
			'name' => 'jump_section',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add a topic',
			'sub_fields' => array (
				array (
					'key' => 'field_5fef82hhfg602',
					'label' => 'Topic Title',
					'name' => 'jump_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0
				),
				array (
					'key' => 'field_56ef827610902',
					'label' => 'Topic Text',
					'name' => 'jump_section_txt',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
				),
				array (
					'key' => 'field_5r099ffm22349',
					'label' => 'Topic Image',
					'name' => 'jump_section_img',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56e53e7a3dd01',
					'label' => 'Section Content',
					'name' => 'post_fl',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'button_label' => 'Add content',
					'min' => '',
					'max' => '',
					'layouts' => array (
						array (
							'key' => '56e53e8afhd73',
							'name' => 'default',
							'label' => 'Default Text',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56ef827s3dd02',
									'label' => 'Text',
									'name' => 'fl_txt',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '56e8900i9e43f',
							'name' => 'two_col_auto',
							'label' => 'Two Column (Auto)',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e62d079e440',
									'label' => 'Text',
									'name' => 'fl_tc_txt',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '7yhnmc87hnv3f',
							'name' => 'two_col',
							'label' => 'Two Columns (2 separate fields)',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e6iuy76e440',
									'label' => 'Text',
									'name' => 'fl_tc_txt1',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
								array (
									'key' => 'field_66tgbp079e440',
									'label' => 'Text',
									'name' => 'fl_tc_txt2',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '57052e9922j47',
							'name' => 'three_column',
							'label' => 'Three Column',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_57052ekkl1048',
									'label' => 'Column #1 Text',
									'name' => 'col_1_txt',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
								array (
									'key' => 'field_5709918d32349',
									'label' => 'Image',
									'name' => 'col_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_57052vmcnj34a',
									'label' => 'Column #2 Text',
									'name' => 'col_2_txt',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '56e53556twd03',
							'name' => 'slider',
							'label' => 'Image Slider',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e53f867504',
									'label' => 'Image Slides',
									'name' => 'fl_slides',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => '',
									'max' => '',
									'layout' => 'block',
									'button_label' => 'Add a slide',
									'sub_fields' => array (
										array (
											'key' => 'field_56e53vnvbbd05',
											'label' => 'Image (700px wide)',
											'name' => 'fl_slide_img',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
										array (
											'key' => 'field_5887lo213dd06',
											'label' => 'Lightbox Image (1280px max-width)',
											'name' => 'fl_slide_lb',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
										array (
											'key' => 'field_56ellp093dd07',
											'label' => 'Caption',
											'name' => 'fl_slide_cap',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '56e540a88767c',
							'name' => 'imgcol',
							'label' => 'Image Column',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e540evhgyd',
									'label' => 'Images',
									'name' => 'fl_imgcol',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 2,
									'max' => 2,
									'layout' => 'block',
									'button_label' => 'Add an image',
									'sub_fields' => array (
										array (
											'key' => 'field_56e655tg6dd5e',
											'label' => 'Image (335px min-width)',
											'name' => 'fl_imgcol_img',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
										array (
											'key' => 'field_56e54avjvhed',
											'label' => 'Lightbox Image (1280px max-width)',
											'name' => 'fl_imgcol_lb',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
										array (
											'key' => 'field_568900o66dd5f',
											'label' => 'Caption',
											'name' => 'fl_imgcol_cap',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '56e500opx85a5',
							'name' => 'txtimg',
							'label' => 'Text/Img Column',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e5444eds5a7',
									'label' => 'Text',
									'name' => 'fl_txtimg_txt',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
								array (
									'key' => 'field_56effrewf85a8',
									'label' => 'Image (440px wide)',
									'name' => 'fl_txtimg_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56e5vcccf85aa',
									'label' => 'Image first?',
									'name' => 'fl_txtimg_rtl',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '56e59354321e1',
							'name' => 'full_bleed',
							'label' => 'Full Bleed Image',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_56e59379gbv7',
									'label' => 'Image (1300 x 570px min-dimensions)',
									'name' => 'fl_fb_img',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_56e56577820e3',
									'label' => 'Caption',
									'name' => 'fl_fb_cap',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						array (
							'key' => '57052e6908895',
							'name' => 'gallery',
							'label' => 'Gallery',
							'display' => 'block',
							'sub_fields' => array (
								array (
									'key' => 'field_570vbbfg32346',
									'label' => 'Gallery Shortcode',
									'name' => 'gallery_shortcode',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
								),
							),
							'min' => '',
							'max' => '',
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;
?>